export const posts = [
    {
        title: "The Riverie by Katathani",
        slug: "the-riverie-by-katathani",
        image: "https://www.thailandbiennale.org/wp-content/uploads/2023/12/IMG_2962_0.jpg",
        rating: 4.5,
        reviews: 125,
        price: 3795,
        cancellation: "Free cancellation",
        city: "Chiang Rai",
        content: "Experience luxury and relaxation at The Riverie, featuring stunning views and exceptional service.",
        type: "Hotel",
    },
    {
        title: "Hi Chiangrai Hotel",
        slug: "hi-chiangrai-hotel",
        image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0e/40/62/14/hall-with-the-pool.jpg?w=700&h=-1&s=1",
        rating: 4.6,
        reviews: 91,
        price: 1243,
        cancellation: "Free cancellation",
        city: "Chiang Rai",
        content: "A modern hotel with a warm atmosphere, perfect for both business and leisure travelers.",
        type: "Hotel",
    },
    {
        title: "Phowadol Resort and Spa",
        slug: "phowadol-resort-and-spa",
        image: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/202986097.jpg?k=2fb317bf878bced4f2325f7e31299d5a5b4c9b38427d85df1b12dd0a42d9dcd2&o=&hp=1",
        rating: 3.6,
        reviews: 28,
        price: 903,
        cancellation: "Free cancellation",
        city: "Chiang Rai",
        content: "Enjoy a peaceful retreat with spa services and beautiful natural surroundings.",
        type: "Hotel",
    },
    {
        title: "Lotus Pang Suan Kaew Hotel",
        slug: "lotus-pang-suan-kaew-hotel",
        image: "https://ak-d.tripcdn.com/images/20010d0000006tw544E6B_W_1280_853_R5.webp?proc=watermark/image_trip1,l_ne,x_16,y_16,w_67,h_16;digimark/t_image,logo_tripbinary;ignoredefaultwm,1A8F",
        rating: 4.0,
        reviews: 169,
        price: 1061,
        cancellation: "",
        city: "Chiang Mai",
        content: "Centrally located with easy access to local attractions and a cozy ambiance.",
        type: "Hotel",
    },
    {
        title: "Le Ville Lanna Chiang Mai Gate Old Town Hotel",
        slug: "le-ville-lanna-chiang-mai-gate-old-town-hotel",
        image: "https://ak-d.tripcdn.com/images/1mc3j12000dh5o1ii4EDE_R_600_400_R5.webp",
        rating: 4.5,
        reviews: 43,
        price: 3144,
        cancellation: "",
        city: "Chiang Mai",
        content: "A charming hotel that blends traditional Thai style with modern comfort.",
        type: "Hotel",
    },
    {
        title: "B2 Resort Boutique & Budget Hotel",
        slug: "b2-resort-boutique-budget-hotel",
        image: "https://ak-d.tripcdn.com/images/1mc6q12000awv7obz43AB_R_600_400_R5.webp",
        rating: 2.8,
        reviews: 54,
        price: 589,
        cancellation: "Free cancellation",
        city: "Chiang Mai",
        content: "Affordable and comfortable accommodations, ideal for budget travelers.",
        type: "Hotel",
    },
    {
        title: "Wyndham Royal Lee Phuket",
        slug: "wyndham-royal-lee-phuket",
        image: "https://ak-d.tripcdn.com/images/20010u000000jiurfB993_W_1280_853_R5.webp?proc=watermark/image_trip1,l_ne,x_16,y_16,w_67,h_16;digimark/t_image,logo_tripbinary;ignoredefaultwm,1A8F",
        rating: 4.9,
        reviews: 342,
        price: 2400,
        cancellation: "",
        city: "Phuket",
        content: "Luxurious beachfront hotel with world-class amenities and breathtaking views.",
        type: "Hotel",
    },
    {
        title: "Meir Jarr",
        slug: "meir-jarr",
        image: "https://ak-d.tripcdn.com/images/1mc4a12000bivju8yCB89_W_1280_853_R5.webp?proc=watermark/image_trip1,l_ne,x_16,y_16,w_67,h_16;digimark/t_image,logo_tripbinary;ignoredefaultwm,1A8F",
        rating: 4.1,
        reviews: 107,
        price: 1073,
        cancellation: "Free cancellation",
        city: "Phuket",
        content: "A stylish hotel offering modern conveniences in a vibrant atmosphere.",
        type: "Hotel",
    },
    {
        title: "Bangsaen Heritage Hotel",
        slug: "bangsaen-heritage-hotel",
        image: "https://ak-d.tripcdn.com/images/220j0v000000k1hcyA834_Z_320_220_R5_D.webp",
        rating: 4.5,
        reviews: 288,
        price: 1966,
        cancellation: "Free cancellation",
        city: "Chonburi",
        content: "Embrace the charm of heritage with comfortable rooms and beachfront access.",
        type: "Hotel",
    },
    {
        title: "Golden Crown Grand Hotel",
        slug: "golden-crown-grand-hotel",
        image: "https://ak-d.tripcdn.com/images/0224d12000cga8844AA01_W_1280_853_R5.webp?proc=watermark/image_trip1,l_ne,x_16,y_16,w_67,h_16;digimark/t_image,logo_tripbinary;ignoredefaultwm,1A8F",
        rating: 3.2,
        reviews: 259,
        price: 1837,
        cancellation: "Free cancellation",
        city: "Hatyai",
        content: "A well-equipped hotel featuring spacious rooms and excellent service.",
        type: "Hotel",
    }
];