### Create a new user
POST http://127.0.0.1:8000/users
Authorization: Bearer <your-jwt-token>
Content-Type: application/json

{
  "name": "Olivia Rodrigo",
  "display_name": "Liv",
  "email": "Olivia.R@example.com",
  "password": "Dejavu",
  "phone_number": "0211314141",
  "address": "32 Cali"
}

###

### Log in as a user
POST http://127.0.0.1:8000/login
Content-Type: application/json

{
  "email": "Hailey.B@example.com",
  "password": "Rhode"
}

###

### Create a group
POST http://127.0.0.1:8000/groups
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1fQ.LYXY7f1sZV6vbiHEyu9skdw-RL4X97nRLKHajZ0h7yw

{
  "name": "Developers Group",
  "user_ids": [4,5]
}

###

### Get group details
GET http://127.0.0.1:8000/groups/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1fQ.LYXY7f1sZV6vbiHEyu9skdw-RL4X97nRLKHajZ0h7yw
Content-Type: application/json

###

### Get user details
GET http://127.0.0.1:8000/users/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1fQ.LYXY7f1sZV6vbiHEyu9skdw-RL4X97nRLKHajZ0h7yw
Content-Type: application/json

