POST http://127.0.0.1:8000/users

{
    "name": "John Doe",
    "display_name": "johnny",
    "email": "john@example.com",
    "password": "password123",
    "phone_number": "1234567890",
    "address": "123 Main Street"
}
